version: '3.4'

networks:
  recommend:
    external:
      name: recommender.localhost

services:
  recommender-db:
    container_name: recommender-db
    image: postgres:12.0
    networks:
      default:
      recommend:
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  recommender-app:
    container_name: recommender-app
    image: jhonsfran/python-dev:3.7-v2
    command: uvicorn --reload --host $HOST --port $PORT --log-level $LOG_LEVEL "app.main:app"
    env_file:
      - .env
    ports:
      - "8000:8000"
      # jupyter notebook
      - "8888:8888"
    expose:
      - 8000
      - 8888
    networks:
      default:
      recommend:
    volumes:
      - .:/opt/app
      # because I don't want to upload data directory to the git repo I use this volume
      - ../data:/opt/app/data
      - python_dependencies:/opt/app/.venv
    depends_on:
      - recommender-db

volumes:
  postgres_data:
  python_dependencies:
