version: '3.4'

networks:
  recommend:
    external:
      name: recommender.localhost

services:
  recommender-db:
    container_name: recommender-db
    image: postgres:12.0
    networks:
      default:
      recommend:
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  recommender-search:
    container_name: recommender-search
    image: getmeili/meilisearch:v0.27.0
    networks:
      default:
      recommend:
    env_file:
      - .env
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

  recommender-app:
    container_name: recommender-app
    image: jhonsfran/python-dev:3.8-v1
    command: uvicorn --reload --host $HOST --port $PORT --log-level $LOG_LEVEL "app.main:app"
    env_file:
      - .env
    ports:
      - "8000:8000"
      # jupyter notebook
      - "8888:8888"
    expose:
      - 8000
      - 8888
    networks:
      default:
      recommend:
    volumes:
      - .:/opt/app
      # because I don't want to upload data directory to the git repo I use this volume
      - ../data:/opt/app/data
      - python_dependencies:/opt/app/.venv
    depends_on:
      - recommender-db

  recommender-login:
    container_name: recommender-login
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    env_file:
      - .env
    ports:
      - "3567:3567"
    expose:
      - 3567
    networks:
      default:
      recommend:
    depends_on:
      - recommender-db

volumes:
  postgres_data:
  python_dependencies:
  meilisearch_data:
