"""update 5

Revision ID: 050c022b34e8
Revises: 388ca6628f15
Create Date: 2022-05-24 06:18:44.481388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050c022b34e8'
down_revision = '388ca6628f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
