"""init

Revision ID: 051f512804af
Revises: 
Create Date: 2021-07-05 13:43:12.387653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051f512804af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # USERS
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_full_name"), "user", ["full_name"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)


    # ITEMS
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_description"), "item", ["description"], unique=False)
    op.create_index(op.f("ix_item_id"), "item", ["id"], unique=False)
    op.create_index(op.f("ix_item_title"), "item", ["title"], unique=False)


    # COPIES
    op.create_table(
        "copy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("copy_title", sa.String(), nullable=False),
        sa.Column("title_id", sa.String(), nullable=True),
        sa.Column("medium_type", sa.String(), nullable=True),
        sa.Column("pr_classmark", sa.String(), nullable=True),
        sa.Column("shelfmark", sa.String(), nullable=True),
        sa.Column("bar_code", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_copy_title"), "copy", ["copy_title"], unique=False)
    op.create_index(op.f("ix_copy_id"), "copy", ["id"], unique=False)
    op.create_index(op.f("ix_copy_title_id"), "copy", ["title_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # COPIES
    op.drop_index(op.f("ix_copy_title_id"), table_name="copy")
    op.drop_index(op.f("ix_copy_id"), table_name="copy")
    op.drop_index(op.f("ix_copy_title"), table_name="copy")
    op.drop_table("copy")

    # ITEMS
    op.drop_index(op.f("ix_item_title"), table_name="item")
    op.drop_index(op.f("ix_item_id"), table_name="item")
    op.drop_index(op.f("ix_item_description"), table_name="item")
    op.drop_table("item")

    # USERS
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_full_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###