"""auto generate tables

Revision ID: 24ada88867d7
Revises: 
Create Date: 2021-07-28 09:37:39.760444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ada88867d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copy_title', sa.String(), nullable=False, comment='Title of the copy'),
    sa.Column('title_id', sa.Integer(), nullable=False, comment='Title ID of the copy. Many copy are created from a Title'),
    sa.Column('medium_type', sa.String(), nullable=True, comment='Media type of the copy'),
    sa.Column('author_name', sa.String(), nullable=True, comment='Author of the Copy'),
    sa.Column('pr_classmark', sa.String(), nullable=True, comment='Information about the copy (library data)'),
    sa.Column('shelfmark', sa.String(), nullable=True, comment='Shelf information (library data)'),
    sa.Column('bar_code', sa.String(), nullable=True, comment='Bar code of the copy  (library data)'),
    sa.Column('location', sa.String(), nullable=True, comment='Library where the copy is located'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_copy_title'), 'copy', ['copy_title'], unique=False)
    op.create_index(op.f('ix_copy_id'), 'copy', ['id'], unique=False)
    op.create_index(op.f('ix_copy_title_id'), 'copy', ['title_id'], unique=False)
    op.create_table('location',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_code', sa.String(), nullable=False, comment='Location code'),
    sa.Column('location_name', sa.String(), nullable=False, comment='Location name'),
    sa.PrimaryKeyConstraint('id', 'location_code')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_index(op.f('ix_location_location_code'), 'location', ['location_code'], unique=False)
    op.create_table('title',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_name', sa.String(), nullable=False, comment='Name of the title'),
    sa.Column('subtitle', sa.String(), nullable=True, comment='Subtitle of the title'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_title_id'), 'title', ['id'], unique=False)
    op.create_index(op.f('ix_title_subtitle'), 'title', ['subtitle'], unique=False)
    op.create_index(op.f('ix_title_title_name'), 'title', ['title_name'], unique=False)
    op.create_table('transactiontype',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trans_type_code', sa.String(), nullable=False, comment='Transaction code type'),
    sa.Column('trans_type_description', sa.String(), nullable=True, comment='Transaction description type'),
    sa.PrimaryKeyConstraint('id', 'trans_type_code')
    )
    op.create_index(op.f('ix_transactiontype_id'), 'transactiontype', ['id'], unique=False)
    op.create_index(op.f('ix_transactiontype_trans_type_code'), 'transactiontype', ['trans_type_code'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_transactiontype_trans_type_code'), table_name='transactiontype')
    op.drop_index(op.f('ix_transactiontype_id'), table_name='transactiontype')
    op.drop_table('transactiontype')
    op.drop_index(op.f('ix_title_title_name'), table_name='title')
    op.drop_index(op.f('ix_title_subtitle'), table_name='title')
    op.drop_index(op.f('ix_title_id'), table_name='title')
    op.drop_table('title')
    op.drop_index(op.f('ix_location_location_code'), table_name='location')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_copy_title_id'), table_name='copy')
    op.drop_index(op.f('ix_copy_id'), table_name='copy')
    op.drop_index(op.f('ix_copy_copy_title'), table_name='copy')
    op.drop_table('copy')
    # ### end Alembic commands ###
