"""

Revision ID: 2b0086505fce
Revises: 64434f06a19b
Create Date: 2022-05-16 08:49:44.456927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0086505fce'
down_revision = '64434f06a19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedents', sa.Integer(), nullable=False, comment='antecedents'),
    sa.Column('consequents', sa.Integer(), nullable=False, comment='consequents'),
    sa.Column('antecedent_support', sa.Float(), nullable=True, comment='antecedent support'),
    sa.Column('consequent_support', sa.Float(), nullable=True, comment='Author of the Copy'),
    sa.Column('support', sa.Float(), nullable=True, comment='support'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='confidence'),
    sa.Column('lift', sa.Float(), nullable=True, comment='lift'),
    sa.Column('leverage', sa.Float(), nullable=True, comment='leverage'),
    sa.Column('conviction', sa.Float(), nullable=True, comment='conviction'),
    sa.Column('antecedent_len', sa.Integer(), nullable=True, comment='antecedent_len'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_antecedents'), 'rule', ['antecedents'], unique=False)
    op.create_index(op.f('ix_rule_consequents'), 'rule', ['consequents'], unique=False)
    op.create_index(op.f('ix_rule_id'), 'rule', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_consequents'), table_name='rule')
    op.drop_index(op.f('ix_rule_antecedents'), table_name='rule')
    op.drop_table('rule')
    # ### end Alembic commands ###
