"""First migrations 3

Revision ID: 2b69aed7c16e
Revises: acd11e3eb0ac
Create Date: 2022-05-22 17:06:53.642814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b69aed7c16e'
down_revision = 'acd11e3eb0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
