"""update 6

Revision ID: 30c0e3bbe39e
Revises: 4dad8f5382fa
Create Date: 2022-05-24 06:38:38.177730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c0e3bbe39e'
down_revision = '4dad8f5382fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
