"""reset migrations

Revision ID: 31900c0ee379
Revises: 
Create Date: 2022-01-11 10:01:12.025365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31900c0ee379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_code', sa.String(), nullable=True, comment='Location code'),
    sa.Column('location_name', sa.String(), nullable=False, comment='Location name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_index(op.f('ix_location_location_code'), 'location', ['location_code'], unique=True)
    op.create_table('transactiontype',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trans_type_code', sa.String(), nullable=True, comment='Transaction code type'),
    sa.Column('trans_type_description', sa.String(), nullable=True, comment='Transaction description type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactiontype_id'), 'transactiontype', ['id'], unique=False)
    op.create_index(op.f('ix_transactiontype_trans_type_code'), 'transactiontype', ['trans_type_code'], unique=True)
    op.create_table('copytransaction',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trans_date_id', sa.Integer(), nullable=False, comment='Date of transaction'),
    sa.Column('trans_type_id', sa.Integer(), nullable=True, comment='Transaction code type'),
    sa.Column('trans_borrower_code', sa.Integer(), nullable=True, comment='Borrower code'),
    sa.Column('trans_location_code_id', sa.Integer(), nullable=True, comment='Location Code'),
    sa.Column('trans_tittle_code_id', sa.Integer(), nullable=True, comment='Title Code'),
    sa.Column('trans_copy_code_id', sa.Integer(), nullable=True, comment='Copy code'),
    sa.Column('trans_borrower_deleted', sa.Integer(), nullable=True, comment='Whether if the borrower was deleted or not'),
    sa.ForeignKeyConstraint(['trans_copy_code_id'], ['copy.id'], ),
    sa.ForeignKeyConstraint(['trans_date_id'], ['date.id'], ),
    sa.ForeignKeyConstraint(['trans_location_code_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['trans_tittle_code_id'], ['title.id'], ),
    sa.ForeignKeyConstraint(['trans_type_id'], ['transactiontype.id'], ),
    sa.PrimaryKeyConstraint('id', 'trans_date_id')
    )
    op.create_index(op.f('ix_copytransaction_id'), 'copytransaction', ['id'], unique=False)
    op.create_index(op.f('ix_copytransaction_trans_borrower_code'), 'copytransaction', ['trans_borrower_code'], unique=False)
    op.create_index(op.f('ix_copytransaction_trans_copy_code_id'), 'copytransaction', ['trans_copy_code_id'], unique=False)
    op.create_index(op.f('ix_copytransaction_trans_date_id'), 'copytransaction', ['trans_date_id'], unique=False)
    op.create_index(op.f('ix_copytransaction_trans_location_code_id'), 'copytransaction', ['trans_location_code_id'], unique=False)
    op.create_index(op.f('ix_copytransaction_trans_tittle_code_id'), 'copytransaction', ['trans_tittle_code_id'], unique=False)
    op.create_index(op.f('ix_copytransaction_trans_type_id'), 'copytransaction', ['trans_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copytransaction_trans_type_id'), table_name='copytransaction')
    op.drop_index(op.f('ix_copytransaction_trans_tittle_code_id'), table_name='copytransaction')
    op.drop_index(op.f('ix_copytransaction_trans_location_code_id'), table_name='copytransaction')
    op.drop_index(op.f('ix_copytransaction_trans_date_id'), table_name='copytransaction')
    op.drop_index(op.f('ix_copytransaction_trans_copy_code_id'), table_name='copytransaction')
    op.drop_index(op.f('ix_copytransaction_trans_borrower_code'), table_name='copytransaction')
    op.drop_index(op.f('ix_copytransaction_id'), table_name='copytransaction')
    op.drop_table('copytransaction')
    op.drop_index(op.f('ix_transactiontype_trans_type_code'), table_name='transactiontype')
    op.drop_index(op.f('ix_transactiontype_id'), table_name='transactiontype')
    op.drop_table('transactiontype')
    op.drop_index(op.f('ix_location_location_code'), table_name='location')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
