"""update 4

Revision ID: 388ca6628f15
Revises: be0fca24b190
Create Date: 2022-05-24 06:09:29.912456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388ca6628f15'
down_revision = 'be0fca24b190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
