"""update 6

Revision ID: 4dad8f5382fa
Revises: 050c022b34e8
Create Date: 2022-05-24 06:33:04.054110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dad8f5382fa'
down_revision = '050c022b34e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
