"""First migrations

Revision ID: 5bdb03ade3d5
Revises: 
Create Date: 2022-05-22 17:02:58.611384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdb03ade3d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedents_id', sa.Integer(), nullable=False, comment='antecedents'),
    sa.Column('consequents_id', sa.Integer(), nullable=False, comment='consequents'),
    sa.Column('antecedent_support', sa.Float(), nullable=True, comment='antecedent support'),
    sa.Column('consequent_support', sa.Float(), nullable=True, comment='Author of the Copy'),
    sa.Column('support', sa.Float(), nullable=True, comment='support'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='confidence'),
    sa.Column('lift', sa.Float(), nullable=True, comment='lift'),
    sa.Column('leverage', sa.Float(), nullable=True, comment='leverage'),
    sa.Column('conviction', sa.Float(), nullable=True, comment='conviction'),
    sa.ForeignKeyConstraint(['antecedents_id'], ['copy.id'], ),
    sa.ForeignKeyConstraint(['consequents_id'], ['copy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_antecedents_id'), 'rule', ['antecedents_id'], unique=False)
    op.create_index(op.f('ix_rule_consequents_id'), 'rule', ['consequents_id'], unique=False)
    op.create_index(op.f('ix_rule_id'), 'rule', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_consequents_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_antecedents_id'), table_name='rule')
    op.drop_table('rule')
    # ### end Alembic commands ###
