"""Add Date dimension

Revision ID: 5ddf5387e4dc
Revises: 24ada88867d7
Create Date: 2021-08-06 07:36:53.686082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddf5387e4dc'
down_revision = '24ada88867d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Date dimension time'),
    sa.Column('date_format', sa.String(), nullable=False, comment='Date String dimension time'),
    sa.Column('day_week', sa.Integer(), nullable=False, comment='Number day of the week'),
    sa.Column('day_name', sa.String(), nullable=False, comment='Name of the Day'),
    sa.Column('day_month', sa.Integer(), nullable=False, comment='Number day of the month'),
    sa.Column('day_year', sa.Integer(), nullable=False, comment='Number Day of the year'),
    sa.Column('month', sa.Integer(), nullable=False, comment='Number of the month'),
    sa.Column('month_name', sa.String(), nullable=False, comment='Name of the Month'),
    sa.Column('month_number_days', sa.Integer(), nullable=False, comment='How many days has this month'),
    sa.Column('week', sa.Integer(), nullable=False, comment='Week of the year'),
    sa.Column('quarter', sa.Integer(), nullable=False, comment='Quarter of the year'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Year of the year'),
    sa.Column('semester', sa.Integer(), nullable=False, comment='Semester of the year'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_date'), 'date', ['date'], unique=False)
    op.create_index(op.f('ix_date_date_format'), 'date', ['date_format'], unique=False)
    op.create_index(op.f('ix_date_id'), 'date', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_date_id'), table_name='date')
    op.drop_index(op.f('ix_date_date_format'), table_name='date')
    op.drop_index(op.f('ix_date_date'), table_name='date')
    op.drop_table('date')
    # ### end Alembic commands ###
