"""Added account table

Revision ID: 688f7021076a
Revises: 30c0e3bbe39e
Create Date: 2022-05-24 06:45:04.144180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688f7021076a'
down_revision = '30c0e3bbe39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
