"""

Revision ID: 8e81a8ffe5bd
Revises: 2b0086505fce
Create Date: 2022-05-16 08:54:35.993289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e81a8ffe5bd'
down_revision = '2b0086505fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'antecedent_len')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('antecedent_len', sa.INTEGER(), autoincrement=False, nullable=True, comment='antecedent_len'))
    # ### end Alembic commands ###
