"""First migrations 2

Revision ID: acd11e3eb0ac
Revises: 5bdb03ade3d5
Create Date: 2022-05-22 17:06:20.886314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd11e3eb0ac'
down_revision = '5bdb03ade3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
