"""update 3

Revision ID: be0fca24b190
Revises: ce168b9430a4
Create Date: 2022-05-22 18:43:12.178173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0fca24b190'
down_revision = 'ce168b9430a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
