"""update migrations

Revision ID: ce168b9430a4
Revises: 2b69aed7c16e
Create Date: 2022-05-22 17:30:26.216133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce168b9430a4'
down_revision = '2b69aed7c16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
