"""update 6

Revision ID: ced37b0f3266
Revises: 688f7021076a
Create Date: 2022-05-24 07:15:30.552172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced37b0f3266'
down_revision = '688f7021076a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
